version: '3.3'

services:
  python2:
    image: reisraff/python2:latest
    container_name: python2
    build:
      context: ./containers/python
      args:
        - PY_VERSION=2.7
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  python3:
    image: reisraff/python3:latest
    container_name: python3
    build:
      context: ./containers/python
      args:
        - PY_VERSION=3
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  php:
    image: reisraff/php:latest
    container_name: php
    build:
      context: ./containers/php
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    volumes:
      - "~/Projects:/home/docker/Projects"
    networks:
      - default
    entrypoint: "/home/docker/run.sh"

  javascript:
    image: reisraff/javascript:latest
    container_name: javascript
    build:
      context: ./containers/javascript
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "~/Projects:/home/docker/Projects"
    entrypoint: "/home/docker/run.sh"

  mysql:
    image: reisraff/mysql:latest
    container_name: mysql
    build:
      context: ./containers/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_PORT=3306
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    networks:
      default:
        aliases:
          - mysql.dockerlink

  kali:
    image: reisraff/kali:latest
    container_name: kali
    build:
      context: ./containers/kali

networks:
  default:
