version: '3.4'

services:
  python2:
    image: reisraff/python:2
    container_name: python2
    build:
      context: ./containers/python
      args:
        PY_VERSION: 2.7
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default

  python3:
    image: reisraff/python:3
    container_name: python3
    build:
      context: ./containers/python
      args:
        PY_VERSION: 3
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - default

  php7.2:
    image: reisraff/php:7.2
    container_name: php
    build:
      context: ./containers/php
      args:
        PHP_VERSION: 7.2
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    networks:
      - default

  php7.3:
    image: reisraff/php:7.3
    container_name: php
    build:
      context: ./containers/php
      args:
        PHP_VERSION: 7.3
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8080:8080"
    networks:
      - default

  node9:
    image: reisraff/node:9
    container_name: node
    build:
      context: ./containers/node
      args:
        NODE_VERSION: 9
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default
    privileged: true

  node8:
    image: reisraff/node:8
    container_name: node
    build:
      context: ./containers/node
      args:
        NODE_VERSION: 8
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default
    privileged: true

  node10:
    image: reisraff/node:10
    container_name: node
    build:
      context: ./containers/node
      args:
        NODE_VERSION: 10
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default
    privileged: true

  node11:
    image: reisraff/node:11
    container_name: node
    build:
      context: ./containers/node
      args:
        NODE_VERSION: 11
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default
    privileged: true

  node12:
    image: reisraff/node:12
    container_name: node
    build:
      context: ./containers/node
      args:
        NODE_VERSION: 12
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - default
    privileged: true

  mysql:
    image: reisraff/mysql:latest
    container_name: mysql
    build:
      context: ./containers/mysql
      args:
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_PORT=3306
    ports:
      - "127.0.0.1:3306:3306"
    expose:
      - "3306"
    networks:
      default:
        aliases:
          - mysql.dockerlink

  postgres:
    image: reisraff/postgres:latest
    container_name: postgres
    build:
      context: ./containers/postgres
      args:
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      default:
        aliases:
          - postgres.dockerlink

  kali:
    image: reisraff/kali:latest
    container_name: kali
    build:
      context: ./containers/kali
      args:
        HOSTUSER: ${HOSTUSER:-docker}
        HOSTUID: ${HOSTUID:-1000}
        HOSTGID: ${HOSTGID:-1000}
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=0
    networks:
      - default
    privileged: true

networks:
  default:
